CREATE TABLE IF NOT EXISTS izkaznice (
    id INT UNSIGNED AUTO_INCREMENT NOT NULL PRIMARY KEY,
ALTER TABLE izkaznice ADD COLUMN cc1Mislav INT UNSIGNED NOT NULL;
ALTER TABLE izkaznice ADD COLUMN cc2Stipe INT UNSIGNED NOT NULL;
ALTER TABLE izkaznice ADD COLUMN cc3Luka INT UNSIGNED NOT NULL;
ALTER TABLE izkaznice ADD COLUMN cc4Tanja INT UNSIGNED NOT NULL;
ALTER TABLE izkaznice ADD COLUMN cc5Martina INT UNSIGNED NOT NULL;
ALTER TABLE izkaznice ADD COLUMN cc6Matea INT UNSIGNED NOT NULL;
)ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS clanovi(
    id INT UNSIGNED AUTO_INCREMENT NOT NULL PRIMARY KEY,
    Matković VARCHAR(100) NOT NULL,
    Perić VARCHAR(100) NOT NULL,
    Sedmak VARCHAR(100) NOT NULL,
    Marić VARCHAR(100) NOT NULL,
    Barić VARCHAR(100) NOT NULL,
    Bačić VARCHAR(100) NOT NULL
)ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS filmovi (
    id INT UNSIGNED AUTO_INCREMENT NOT NULL PRIMARY KEY,
    Star Wars VARCHAR(100) NOT NULL,
    Rocky VARCHAR(100) NOT NULL,
    Femme Fatale VARCHAR(100) NOT NULL,
    Naked Gun VARCHAR(100) NOT NULL,
    Let Me Down VARCHAR(100) NOT NULL,
    Slasher VARCHAR(100) NOT NULL
)ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS zanrovi (
    id INT UNSIGNED AUTO_INCREMENT NOT NULL PRIMARY KEY,
    Sci-Fi - Star Wars VARCHAR(20) NOT NULL,
    Akcija - Rocky VARCHAR(20) NOT NULL,
    Drama - Femme Fatale VARCHAR(20) NOT NULL,
    Komedija - Naked Gun VARCHAR(20) NOT NULL,
    Teen film - Let Me Down VARCHAR(20) NOT NULL,
    Horor - Slasher VARCHAR(20) NOT NULL
)ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS cjenik (
    id INT UNSIGNED AUTO_INCREMENT NOT NULL PRIMARY KEY,
    Stari filmovi - Star Wars, Rocky, Naked Gun - 4 eura VARCHAR(50) NOT NULL,
    Novi filmovi - Femme Fatale, Let Me Down, Slasher - 8 eura VARCHAR(50) NOT NULL
)ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS verzije filmova (
    id INT UNSIGNED AUTO_INCREMENT NOT NULL PRIMARY KEY,
    Stari filmovi - DVD VARCHAR(20) NOT NULL,
    Novi filmovi - BluRay VARCHAR(20) NOT NULL
)ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS posudbe filmova (
    id INT UNSIGNED AUTO_INCREMENT NOT NULL PRIMARY KEY,
    Rok posudbe - Tjedan dana VARCHAR(30) NOT NULL,
    Zakasnina po danu - 1.5 eura VARCHAR(30) NOT NULL
)ENGINE=InnoDB;